<?xml version="1.0" encoding="UTF-8" ?>
<Package name="QMatic" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="behavior_1" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs>
        <Dialog name="qmatic" src="qmatic/qmatic.dlg" />
    </Dialogs>
    <Resources>
        <File name="customerquery" src="customerquery.py" />
        <File name="pepper" src="html/css/pepper.css" />
        <File name="logo" src="html/img/logo.png" />
        <File name="pepper" src="html/img/pepper.png" />
        <File name="index" src="html/index.html" />
        <File name="app_script" src="html/js/app_script.js" />
        <File name="jquery-2.1.4.min" src="html/js/jquery-2.1.4.min.js" />
        <File name="numpad" src="html/js/numpad.js" />
        <File name="qimessaging_helper" src="html/js/qimessaging_helper.js" />
        <File name="main" src="main.py" />
        <File name="notification" src="notification.py" />
        <File name="__init__" src="pytz/__init__.py" />
        <File name="__init__" src="pytz/__init__.pyc" />
        <File name="exceptions" src="pytz/exceptions.py" />
        <File name="exceptions" src="pytz/exceptions.pyc" />
        <File name="lazy" src="pytz/lazy.py" />
        <File name="lazy" src="pytz/lazy.pyc" />
        <File name="reference" src="pytz/reference.py" />
        <File name="test_docs" src="pytz/tests/test_docs.py" />
        <File name="test_lazy" src="pytz/tests/test_lazy.py" />
        <File name="test_tzinfo" src="pytz/tests/test_tzinfo.py" />
        <File name="tzfile" src="pytz/tzfile.py" />
        <File name="tzfile" src="pytz/tzfile.pyc" />
        <File name="tzinfo" src="pytz/tzinfo.py" />
        <File name="tzinfo" src="pytz/tzinfo.pyc" />
        <File name="Abidjan" src="pytz/zoneinfo/Africa/Abidjan" />
        <File name="Accra" src="pytz/zoneinfo/Africa/Accra" />
        <File name="Addis_Ababa" src="pytz/zoneinfo/Africa/Addis_Ababa" />
        <File name="Algiers" src="pytz/zoneinfo/Africa/Algiers" />
        <File name="Asmara" src="pytz/zoneinfo/Africa/Asmara" />
        <File name="Asmera" src="pytz/zoneinfo/Africa/Asmera" />
        <File name="Bamako" src="pytz/zoneinfo/Africa/Bamako" />
        <File name="Bangui" src="pytz/zoneinfo/Africa/Bangui" />
        <File name="Banjul" src="pytz/zoneinfo/Africa/Banjul" />
        <File name="Bissau" src="pytz/zoneinfo/Africa/Bissau" />
        <File name="Blantyre" src="pytz/zoneinfo/Africa/Blantyre" />
        <File name="Brazzaville" src="pytz/zoneinfo/Africa/Brazzaville" />
        <File name="Bujumbura" src="pytz/zoneinfo/Africa/Bujumbura" />
        <File name="Cairo" src="pytz/zoneinfo/Africa/Cairo" />
        <File name="Casablanca" src="pytz/zoneinfo/Africa/Casablanca" />
        <File name="Ceuta" src="pytz/zoneinfo/Africa/Ceuta" />
        <File name="Conakry" src="pytz/zoneinfo/Africa/Conakry" />
        <File name="Dakar" src="pytz/zoneinfo/Africa/Dakar" />
        <File name="Dar_es_Salaam" src="pytz/zoneinfo/Africa/Dar_es_Salaam" />
        <File name="Djibouti" src="pytz/zoneinfo/Africa/Djibouti" />
        <File name="Douala" src="pytz/zoneinfo/Africa/Douala" />
        <File name="El_Aaiun" src="pytz/zoneinfo/Africa/El_Aaiun" />
        <File name="Freetown" src="pytz/zoneinfo/Africa/Freetown" />
        <File name="Gaborone" src="pytz/zoneinfo/Africa/Gaborone" />
        <File name="Harare" src="pytz/zoneinfo/Africa/Harare" />
        <File name="Johannesburg" src="pytz/zoneinfo/Africa/Johannesburg" />
        <File name="Juba" src="pytz/zoneinfo/Africa/Juba" />
        <File name="Kampala" src="pytz/zoneinfo/Africa/Kampala" />
        <File name="Khartoum" src="pytz/zoneinfo/Africa/Khartoum" />
        <File name="Kigali" src="pytz/zoneinfo/Africa/Kigali" />
        <File name="Kinshasa" src="pytz/zoneinfo/Africa/Kinshasa" />
        <File name="Lagos" src="pytz/zoneinfo/Africa/Lagos" />
        <File name="Libreville" src="pytz/zoneinfo/Africa/Libreville" />
        <File name="Lome" src="pytz/zoneinfo/Africa/Lome" />
        <File name="Luanda" src="pytz/zoneinfo/Africa/Luanda" />
        <File name="Lubumbashi" src="pytz/zoneinfo/Africa/Lubumbashi" />
        <File name="Lusaka" src="pytz/zoneinfo/Africa/Lusaka" />
        <File name="Malabo" src="pytz/zoneinfo/Africa/Malabo" />
        <File name="Maputo" src="pytz/zoneinfo/Africa/Maputo" />
        <File name="Maseru" src="pytz/zoneinfo/Africa/Maseru" />
        <File name="Mbabane" src="pytz/zoneinfo/Africa/Mbabane" />
        <File name="Mogadishu" src="pytz/zoneinfo/Africa/Mogadishu" />
        <File name="Monrovia" src="pytz/zoneinfo/Africa/Monrovia" />
        <File name="Nairobi" src="pytz/zoneinfo/Africa/Nairobi" />
        <File name="Ndjamena" src="pytz/zoneinfo/Africa/Ndjamena" />
        <File name="Niamey" src="pytz/zoneinfo/Africa/Niamey" />
        <File name="Nouakchott" src="pytz/zoneinfo/Africa/Nouakchott" />
        <File name="Ouagadougou" src="pytz/zoneinfo/Africa/Ouagadougou" />
        <File name="Porto-Novo" src="pytz/zoneinfo/Africa/Porto-Novo" />
        <File name="Sao_Tome" src="pytz/zoneinfo/Africa/Sao_Tome" />
        <File name="Timbuktu" src="pytz/zoneinfo/Africa/Timbuktu" />
        <File name="Tripoli" src="pytz/zoneinfo/Africa/Tripoli" />
        <File name="Tunis" src="pytz/zoneinfo/Africa/Tunis" />
        <File name="Windhoek" src="pytz/zoneinfo/Africa/Windhoek" />
        <File name="Adak" src="pytz/zoneinfo/America/Adak" />
        <File name="Anchorage" src="pytz/zoneinfo/America/Anchorage" />
        <File name="Anguilla" src="pytz/zoneinfo/America/Anguilla" />
        <File name="Antigua" src="pytz/zoneinfo/America/Antigua" />
        <File name="Araguaina" src="pytz/zoneinfo/America/Araguaina" />
        <File name="Buenos_Aires" src="pytz/zoneinfo/America/Argentina/Buenos_Aires" />
        <File name="Catamarca" src="pytz/zoneinfo/America/Argentina/Catamarca" />
        <File name="ComodRivadavia" src="pytz/zoneinfo/America/Argentina/ComodRivadavia" />
        <File name="Cordoba" src="pytz/zoneinfo/America/Argentina/Cordoba" />
        <File name="Jujuy" src="pytz/zoneinfo/America/Argentina/Jujuy" />
        <File name="La_Rioja" src="pytz/zoneinfo/America/Argentina/La_Rioja" />
        <File name="Mendoza" src="pytz/zoneinfo/America/Argentina/Mendoza" />
        <File name="Rio_Gallegos" src="pytz/zoneinfo/America/Argentina/Rio_Gallegos" />
        <File name="Salta" src="pytz/zoneinfo/America/Argentina/Salta" />
        <File name="San_Juan" src="pytz/zoneinfo/America/Argentina/San_Juan" />
        <File name="San_Luis" src="pytz/zoneinfo/America/Argentina/San_Luis" />
        <File name="Tucuman" src="pytz/zoneinfo/America/Argentina/Tucuman" />
        <File name="Ushuaia" src="pytz/zoneinfo/America/Argentina/Ushuaia" />
        <File name="Aruba" src="pytz/zoneinfo/America/Aruba" />
        <File name="Asuncion" src="pytz/zoneinfo/America/Asuncion" />
        <File name="Atikokan" src="pytz/zoneinfo/America/Atikokan" />
        <File name="Atka" src="pytz/zoneinfo/America/Atka" />
        <File name="Bahia" src="pytz/zoneinfo/America/Bahia" />
        <File name="Bahia_Banderas" src="pytz/zoneinfo/America/Bahia_Banderas" />
        <File name="Barbados" src="pytz/zoneinfo/America/Barbados" />
        <File name="Belem" src="pytz/zoneinfo/America/Belem" />
        <File name="Belize" src="pytz/zoneinfo/America/Belize" />
        <File name="Blanc-Sablon" src="pytz/zoneinfo/America/Blanc-Sablon" />
        <File name="Boa_Vista" src="pytz/zoneinfo/America/Boa_Vista" />
        <File name="Bogota" src="pytz/zoneinfo/America/Bogota" />
        <File name="Boise" src="pytz/zoneinfo/America/Boise" />
        <File name="Buenos_Aires" src="pytz/zoneinfo/America/Buenos_Aires" />
        <File name="Cambridge_Bay" src="pytz/zoneinfo/America/Cambridge_Bay" />
        <File name="Campo_Grande" src="pytz/zoneinfo/America/Campo_Grande" />
        <File name="Cancun" src="pytz/zoneinfo/America/Cancun" />
        <File name="Caracas" src="pytz/zoneinfo/America/Caracas" />
        <File name="Catamarca" src="pytz/zoneinfo/America/Catamarca" />
        <File name="Cayenne" src="pytz/zoneinfo/America/Cayenne" />
        <File name="Cayman" src="pytz/zoneinfo/America/Cayman" />
        <File name="Chicago" src="pytz/zoneinfo/America/Chicago" />
        <File name="Chihuahua" src="pytz/zoneinfo/America/Chihuahua" />
        <File name="Coral_Harbour" src="pytz/zoneinfo/America/Coral_Harbour" />
        <File name="Cordoba" src="pytz/zoneinfo/America/Cordoba" />
        <File name="Costa_Rica" src="pytz/zoneinfo/America/Costa_Rica" />
        <File name="Creston" src="pytz/zoneinfo/America/Creston" />
        <File name="Cuiaba" src="pytz/zoneinfo/America/Cuiaba" />
        <File name="Curacao" src="pytz/zoneinfo/America/Curacao" />
        <File name="Danmarkshavn" src="pytz/zoneinfo/America/Danmarkshavn" />
        <File name="Dawson" src="pytz/zoneinfo/America/Dawson" />
        <File name="Dawson_Creek" src="pytz/zoneinfo/America/Dawson_Creek" />
        <File name="Denver" src="pytz/zoneinfo/America/Denver" />
        <File name="Detroit" src="pytz/zoneinfo/America/Detroit" />
        <File name="Dominica" src="pytz/zoneinfo/America/Dominica" />
        <File name="Edmonton" src="pytz/zoneinfo/America/Edmonton" />
        <File name="Eirunepe" src="pytz/zoneinfo/America/Eirunepe" />
        <File name="El_Salvador" src="pytz/zoneinfo/America/El_Salvador" />
        <File name="Ensenada" src="pytz/zoneinfo/America/Ensenada" />
        <File name="Fort_Nelson" src="pytz/zoneinfo/America/Fort_Nelson" />
        <File name="Fort_Wayne" src="pytz/zoneinfo/America/Fort_Wayne" />
        <File name="Fortaleza" src="pytz/zoneinfo/America/Fortaleza" />
        <File name="Glace_Bay" src="pytz/zoneinfo/America/Glace_Bay" />
        <File name="Godthab" src="pytz/zoneinfo/America/Godthab" />
        <File name="Goose_Bay" src="pytz/zoneinfo/America/Goose_Bay" />
        <File name="Grand_Turk" src="pytz/zoneinfo/America/Grand_Turk" />
        <File name="Grenada" src="pytz/zoneinfo/America/Grenada" />
        <File name="Guadeloupe" src="pytz/zoneinfo/America/Guadeloupe" />
        <File name="Guatemala" src="pytz/zoneinfo/America/Guatemala" />
        <File name="Guayaquil" src="pytz/zoneinfo/America/Guayaquil" />
        <File name="Guyana" src="pytz/zoneinfo/America/Guyana" />
        <File name="Halifax" src="pytz/zoneinfo/America/Halifax" />
        <File name="Havana" src="pytz/zoneinfo/America/Havana" />
        <File name="Hermosillo" src="pytz/zoneinfo/America/Hermosillo" />
        <File name="Indianapolis" src="pytz/zoneinfo/America/Indiana/Indianapolis" />
        <File name="Knox" src="pytz/zoneinfo/America/Indiana/Knox" />
        <File name="Marengo" src="pytz/zoneinfo/America/Indiana/Marengo" />
        <File name="Petersburg" src="pytz/zoneinfo/America/Indiana/Petersburg" />
        <File name="Tell_City" src="pytz/zoneinfo/America/Indiana/Tell_City" />
        <File name="Vevay" src="pytz/zoneinfo/America/Indiana/Vevay" />
        <File name="Vincennes" src="pytz/zoneinfo/America/Indiana/Vincennes" />
        <File name="Winamac" src="pytz/zoneinfo/America/Indiana/Winamac" />
        <File name="Indianapolis" src="pytz/zoneinfo/America/Indianapolis" />
        <File name="Inuvik" src="pytz/zoneinfo/America/Inuvik" />
        <File name="Iqaluit" src="pytz/zoneinfo/America/Iqaluit" />
        <File name="Jamaica" src="pytz/zoneinfo/America/Jamaica" />
        <File name="Jujuy" src="pytz/zoneinfo/America/Jujuy" />
        <File name="Juneau" src="pytz/zoneinfo/America/Juneau" />
        <File name="Louisville" src="pytz/zoneinfo/America/Kentucky/Louisville" />
        <File name="Monticello" src="pytz/zoneinfo/America/Kentucky/Monticello" />
        <File name="Knox_IN" src="pytz/zoneinfo/America/Knox_IN" />
        <File name="Kralendijk" src="pytz/zoneinfo/America/Kralendijk" />
        <File name="La_Paz" src="pytz/zoneinfo/America/La_Paz" />
        <File name="Lima" src="pytz/zoneinfo/America/Lima" />
        <File name="Los_Angeles" src="pytz/zoneinfo/America/Los_Angeles" />
        <File name="Louisville" src="pytz/zoneinfo/America/Louisville" />
        <File name="Lower_Princes" src="pytz/zoneinfo/America/Lower_Princes" />
        <File name="Maceio" src="pytz/zoneinfo/America/Maceio" />
        <File name="Managua" src="pytz/zoneinfo/America/Managua" />
        <File name="Manaus" src="pytz/zoneinfo/America/Manaus" />
        <File name="Marigot" src="pytz/zoneinfo/America/Marigot" />
        <File name="Martinique" src="pytz/zoneinfo/America/Martinique" />
        <File name="Matamoros" src="pytz/zoneinfo/America/Matamoros" />
        <File name="Mazatlan" src="pytz/zoneinfo/America/Mazatlan" />
        <File name="Mendoza" src="pytz/zoneinfo/America/Mendoza" />
        <File name="Menominee" src="pytz/zoneinfo/America/Menominee" />
        <File name="Merida" src="pytz/zoneinfo/America/Merida" />
        <File name="Metlakatla" src="pytz/zoneinfo/America/Metlakatla" />
        <File name="Mexico_City" src="pytz/zoneinfo/America/Mexico_City" />
        <File name="Miquelon" src="pytz/zoneinfo/America/Miquelon" />
        <File name="Moncton" src="pytz/zoneinfo/America/Moncton" />
        <File name="Monterrey" src="pytz/zoneinfo/America/Monterrey" />
        <File name="Montevideo" src="pytz/zoneinfo/America/Montevideo" />
        <File name="Montreal" src="pytz/zoneinfo/America/Montreal" />
        <File name="Montserrat" src="pytz/zoneinfo/America/Montserrat" />
        <File name="Nassau" src="pytz/zoneinfo/America/Nassau" />
        <File name="New_York" src="pytz/zoneinfo/America/New_York" />
        <File name="Nipigon" src="pytz/zoneinfo/America/Nipigon" />
        <File name="Nome" src="pytz/zoneinfo/America/Nome" />
        <File name="Noronha" src="pytz/zoneinfo/America/Noronha" />
        <File name="Beulah" src="pytz/zoneinfo/America/North_Dakota/Beulah" />
        <File name="Center" src="pytz/zoneinfo/America/North_Dakota/Center" />
        <File name="New_Salem" src="pytz/zoneinfo/America/North_Dakota/New_Salem" />
        <File name="Ojinaga" src="pytz/zoneinfo/America/Ojinaga" />
        <File name="Panama" src="pytz/zoneinfo/America/Panama" />
        <File name="Pangnirtung" src="pytz/zoneinfo/America/Pangnirtung" />
        <File name="Paramaribo" src="pytz/zoneinfo/America/Paramaribo" />
        <File name="Phoenix" src="pytz/zoneinfo/America/Phoenix" />
        <File name="Port-au-Prince" src="pytz/zoneinfo/America/Port-au-Prince" />
        <File name="Port_of_Spain" src="pytz/zoneinfo/America/Port_of_Spain" />
        <File name="Porto_Acre" src="pytz/zoneinfo/America/Porto_Acre" />
        <File name="Porto_Velho" src="pytz/zoneinfo/America/Porto_Velho" />
        <File name="Puerto_Rico" src="pytz/zoneinfo/America/Puerto_Rico" />
        <File name="Punta_Arenas" src="pytz/zoneinfo/America/Punta_Arenas" />
        <File name="Rainy_River" src="pytz/zoneinfo/America/Rainy_River" />
        <File name="Rankin_Inlet" src="pytz/zoneinfo/America/Rankin_Inlet" />
        <File name="Recife" src="pytz/zoneinfo/America/Recife" />
        <File name="Regina" src="pytz/zoneinfo/America/Regina" />
        <File name="Resolute" src="pytz/zoneinfo/America/Resolute" />
        <File name="Rio_Branco" src="pytz/zoneinfo/America/Rio_Branco" />
        <File name="Rosario" src="pytz/zoneinfo/America/Rosario" />
        <File name="Santa_Isabel" src="pytz/zoneinfo/America/Santa_Isabel" />
        <File name="Santarem" src="pytz/zoneinfo/America/Santarem" />
        <File name="Santiago" src="pytz/zoneinfo/America/Santiago" />
        <File name="Santo_Domingo" src="pytz/zoneinfo/America/Santo_Domingo" />
        <File name="Sao_Paulo" src="pytz/zoneinfo/America/Sao_Paulo" />
        <File name="Scoresbysund" src="pytz/zoneinfo/America/Scoresbysund" />
        <File name="Shiprock" src="pytz/zoneinfo/America/Shiprock" />
        <File name="Sitka" src="pytz/zoneinfo/America/Sitka" />
        <File name="St_Barthelemy" src="pytz/zoneinfo/America/St_Barthelemy" />
        <File name="St_Johns" src="pytz/zoneinfo/America/St_Johns" />
        <File name="St_Kitts" src="pytz/zoneinfo/America/St_Kitts" />
        <File name="St_Lucia" src="pytz/zoneinfo/America/St_Lucia" />
        <File name="St_Thomas" src="pytz/zoneinfo/America/St_Thomas" />
        <File name="St_Vincent" src="pytz/zoneinfo/America/St_Vincent" />
        <File name="Swift_Current" src="pytz/zoneinfo/America/Swift_Current" />
        <File name="Tegucigalpa" src="pytz/zoneinfo/America/Tegucigalpa" />
        <File name="Thule" src="pytz/zoneinfo/America/Thule" />
        <File name="Thunder_Bay" src="pytz/zoneinfo/America/Thunder_Bay" />
        <File name="Tijuana" src="pytz/zoneinfo/America/Tijuana" />
        <File name="Toronto" src="pytz/zoneinfo/America/Toronto" />
        <File name="Tortola" src="pytz/zoneinfo/America/Tortola" />
        <File name="Vancouver" src="pytz/zoneinfo/America/Vancouver" />
        <File name="Virgin" src="pytz/zoneinfo/America/Virgin" />
        <File name="Whitehorse" src="pytz/zoneinfo/America/Whitehorse" />
        <File name="Winnipeg" src="pytz/zoneinfo/America/Winnipeg" />
        <File name="Yakutat" src="pytz/zoneinfo/America/Yakutat" />
        <File name="Yellowknife" src="pytz/zoneinfo/America/Yellowknife" />
        <File name="Casey" src="pytz/zoneinfo/Antarctica/Casey" />
        <File name="Davis" src="pytz/zoneinfo/Antarctica/Davis" />
        <File name="DumontDUrville" src="pytz/zoneinfo/Antarctica/DumontDUrville" />
        <File name="Macquarie" src="pytz/zoneinfo/Antarctica/Macquarie" />
        <File name="Mawson" src="pytz/zoneinfo/Antarctica/Mawson" />
        <File name="McMurdo" src="pytz/zoneinfo/Antarctica/McMurdo" />
        <File name="Palmer" src="pytz/zoneinfo/Antarctica/Palmer" />
        <File name="Rothera" src="pytz/zoneinfo/Antarctica/Rothera" />
        <File name="South_Pole" src="pytz/zoneinfo/Antarctica/South_Pole" />
        <File name="Syowa" src="pytz/zoneinfo/Antarctica/Syowa" />
        <File name="Troll" src="pytz/zoneinfo/Antarctica/Troll" />
        <File name="Vostok" src="pytz/zoneinfo/Antarctica/Vostok" />
        <File name="Longyearbyen" src="pytz/zoneinfo/Arctic/Longyearbyen" />
        <File name="Aden" src="pytz/zoneinfo/Asia/Aden" />
        <File name="Almaty" src="pytz/zoneinfo/Asia/Almaty" />
        <File name="Amman" src="pytz/zoneinfo/Asia/Amman" />
        <File name="Anadyr" src="pytz/zoneinfo/Asia/Anadyr" />
        <File name="Aqtau" src="pytz/zoneinfo/Asia/Aqtau" />
        <File name="Aqtobe" src="pytz/zoneinfo/Asia/Aqtobe" />
        <File name="Ashgabat" src="pytz/zoneinfo/Asia/Ashgabat" />
        <File name="Ashkhabad" src="pytz/zoneinfo/Asia/Ashkhabad" />
        <File name="Atyrau" src="pytz/zoneinfo/Asia/Atyrau" />
        <File name="Baghdad" src="pytz/zoneinfo/Asia/Baghdad" />
        <File name="Bahrain" src="pytz/zoneinfo/Asia/Bahrain" />
        <File name="Baku" src="pytz/zoneinfo/Asia/Baku" />
        <File name="Bangkok" src="pytz/zoneinfo/Asia/Bangkok" />
        <File name="Barnaul" src="pytz/zoneinfo/Asia/Barnaul" />
        <File name="Beirut" src="pytz/zoneinfo/Asia/Beirut" />
        <File name="Bishkek" src="pytz/zoneinfo/Asia/Bishkek" />
        <File name="Brunei" src="pytz/zoneinfo/Asia/Brunei" />
        <File name="Calcutta" src="pytz/zoneinfo/Asia/Calcutta" />
        <File name="Chita" src="pytz/zoneinfo/Asia/Chita" />
        <File name="Choibalsan" src="pytz/zoneinfo/Asia/Choibalsan" />
        <File name="Chongqing" src="pytz/zoneinfo/Asia/Chongqing" />
        <File name="Chungking" src="pytz/zoneinfo/Asia/Chungking" />
        <File name="Colombo" src="pytz/zoneinfo/Asia/Colombo" />
        <File name="Dacca" src="pytz/zoneinfo/Asia/Dacca" />
        <File name="Damascus" src="pytz/zoneinfo/Asia/Damascus" />
        <File name="Dhaka" src="pytz/zoneinfo/Asia/Dhaka" />
        <File name="Dili" src="pytz/zoneinfo/Asia/Dili" />
        <File name="Dubai" src="pytz/zoneinfo/Asia/Dubai" />
        <File name="Dushanbe" src="pytz/zoneinfo/Asia/Dushanbe" />
        <File name="Famagusta" src="pytz/zoneinfo/Asia/Famagusta" />
        <File name="Gaza" src="pytz/zoneinfo/Asia/Gaza" />
        <File name="Harbin" src="pytz/zoneinfo/Asia/Harbin" />
        <File name="Hebron" src="pytz/zoneinfo/Asia/Hebron" />
        <File name="Ho_Chi_Minh" src="pytz/zoneinfo/Asia/Ho_Chi_Minh" />
        <File name="Hong_Kong" src="pytz/zoneinfo/Asia/Hong_Kong" />
        <File name="Hovd" src="pytz/zoneinfo/Asia/Hovd" />
        <File name="Irkutsk" src="pytz/zoneinfo/Asia/Irkutsk" />
        <File name="Istanbul" src="pytz/zoneinfo/Asia/Istanbul" />
        <File name="Jakarta" src="pytz/zoneinfo/Asia/Jakarta" />
        <File name="Jayapura" src="pytz/zoneinfo/Asia/Jayapura" />
        <File name="Jerusalem" src="pytz/zoneinfo/Asia/Jerusalem" />
        <File name="Kabul" src="pytz/zoneinfo/Asia/Kabul" />
        <File name="Kamchatka" src="pytz/zoneinfo/Asia/Kamchatka" />
        <File name="Karachi" src="pytz/zoneinfo/Asia/Karachi" />
        <File name="Kashgar" src="pytz/zoneinfo/Asia/Kashgar" />
        <File name="Kathmandu" src="pytz/zoneinfo/Asia/Kathmandu" />
        <File name="Katmandu" src="pytz/zoneinfo/Asia/Katmandu" />
        <File name="Khandyga" src="pytz/zoneinfo/Asia/Khandyga" />
        <File name="Kolkata" src="pytz/zoneinfo/Asia/Kolkata" />
        <File name="Krasnoyarsk" src="pytz/zoneinfo/Asia/Krasnoyarsk" />
        <File name="Kuala_Lumpur" src="pytz/zoneinfo/Asia/Kuala_Lumpur" />
        <File name="Kuching" src="pytz/zoneinfo/Asia/Kuching" />
        <File name="Kuwait" src="pytz/zoneinfo/Asia/Kuwait" />
        <File name="Macao" src="pytz/zoneinfo/Asia/Macao" />
        <File name="Macau" src="pytz/zoneinfo/Asia/Macau" />
        <File name="Magadan" src="pytz/zoneinfo/Asia/Magadan" />
        <File name="Makassar" src="pytz/zoneinfo/Asia/Makassar" />
        <File name="Manila" src="pytz/zoneinfo/Asia/Manila" />
        <File name="Muscat" src="pytz/zoneinfo/Asia/Muscat" />
        <File name="Nicosia" src="pytz/zoneinfo/Asia/Nicosia" />
        <File name="Novokuznetsk" src="pytz/zoneinfo/Asia/Novokuznetsk" />
        <File name="Novosibirsk" src="pytz/zoneinfo/Asia/Novosibirsk" />
        <File name="Omsk" src="pytz/zoneinfo/Asia/Omsk" />
        <File name="Oral" src="pytz/zoneinfo/Asia/Oral" />
        <File name="Phnom_Penh" src="pytz/zoneinfo/Asia/Phnom_Penh" />
        <File name="Pontianak" src="pytz/zoneinfo/Asia/Pontianak" />
        <File name="Pyongyang" src="pytz/zoneinfo/Asia/Pyongyang" />
        <File name="Qatar" src="pytz/zoneinfo/Asia/Qatar" />
        <File name="Qyzylorda" src="pytz/zoneinfo/Asia/Qyzylorda" />
        <File name="Rangoon" src="pytz/zoneinfo/Asia/Rangoon" />
        <File name="Riyadh" src="pytz/zoneinfo/Asia/Riyadh" />
        <File name="Saigon" src="pytz/zoneinfo/Asia/Saigon" />
        <File name="Sakhalin" src="pytz/zoneinfo/Asia/Sakhalin" />
        <File name="Samarkand" src="pytz/zoneinfo/Asia/Samarkand" />
        <File name="Seoul" src="pytz/zoneinfo/Asia/Seoul" />
        <File name="Shanghai" src="pytz/zoneinfo/Asia/Shanghai" />
        <File name="Singapore" src="pytz/zoneinfo/Asia/Singapore" />
        <File name="Srednekolymsk" src="pytz/zoneinfo/Asia/Srednekolymsk" />
        <File name="Taipei" src="pytz/zoneinfo/Asia/Taipei" />
        <File name="Tashkent" src="pytz/zoneinfo/Asia/Tashkent" />
        <File name="Tbilisi" src="pytz/zoneinfo/Asia/Tbilisi" />
        <File name="Tehran" src="pytz/zoneinfo/Asia/Tehran" />
        <File name="Tel_Aviv" src="pytz/zoneinfo/Asia/Tel_Aviv" />
        <File name="Thimbu" src="pytz/zoneinfo/Asia/Thimbu" />
        <File name="Thimphu" src="pytz/zoneinfo/Asia/Thimphu" />
        <File name="Tokyo" src="pytz/zoneinfo/Asia/Tokyo" />
        <File name="Tomsk" src="pytz/zoneinfo/Asia/Tomsk" />
        <File name="Ujung_Pandang" src="pytz/zoneinfo/Asia/Ujung_Pandang" />
        <File name="Ulaanbaatar" src="pytz/zoneinfo/Asia/Ulaanbaatar" />
        <File name="Ulan_Bator" src="pytz/zoneinfo/Asia/Ulan_Bator" />
        <File name="Urumqi" src="pytz/zoneinfo/Asia/Urumqi" />
        <File name="Ust-Nera" src="pytz/zoneinfo/Asia/Ust-Nera" />
        <File name="Vientiane" src="pytz/zoneinfo/Asia/Vientiane" />
        <File name="Vladivostok" src="pytz/zoneinfo/Asia/Vladivostok" />
        <File name="Yakutsk" src="pytz/zoneinfo/Asia/Yakutsk" />
        <File name="Yangon" src="pytz/zoneinfo/Asia/Yangon" />
        <File name="Yekaterinburg" src="pytz/zoneinfo/Asia/Yekaterinburg" />
        <File name="Yerevan" src="pytz/zoneinfo/Asia/Yerevan" />
        <File name="Azores" src="pytz/zoneinfo/Atlantic/Azores" />
        <File name="Bermuda" src="pytz/zoneinfo/Atlantic/Bermuda" />
        <File name="Canary" src="pytz/zoneinfo/Atlantic/Canary" />
        <File name="Cape_Verde" src="pytz/zoneinfo/Atlantic/Cape_Verde" />
        <File name="Faeroe" src="pytz/zoneinfo/Atlantic/Faeroe" />
        <File name="Faroe" src="pytz/zoneinfo/Atlantic/Faroe" />
        <File name="Jan_Mayen" src="pytz/zoneinfo/Atlantic/Jan_Mayen" />
        <File name="Madeira" src="pytz/zoneinfo/Atlantic/Madeira" />
        <File name="Reykjavik" src="pytz/zoneinfo/Atlantic/Reykjavik" />
        <File name="South_Georgia" src="pytz/zoneinfo/Atlantic/South_Georgia" />
        <File name="St_Helena" src="pytz/zoneinfo/Atlantic/St_Helena" />
        <File name="Stanley" src="pytz/zoneinfo/Atlantic/Stanley" />
        <File name="ACT" src="pytz/zoneinfo/Australia/ACT" />
        <File name="Adelaide" src="pytz/zoneinfo/Australia/Adelaide" />
        <File name="Brisbane" src="pytz/zoneinfo/Australia/Brisbane" />
        <File name="Broken_Hill" src="pytz/zoneinfo/Australia/Broken_Hill" />
        <File name="Canberra" src="pytz/zoneinfo/Australia/Canberra" />
        <File name="Currie" src="pytz/zoneinfo/Australia/Currie" />
        <File name="Darwin" src="pytz/zoneinfo/Australia/Darwin" />
        <File name="Eucla" src="pytz/zoneinfo/Australia/Eucla" />
        <File name="Hobart" src="pytz/zoneinfo/Australia/Hobart" />
        <File name="LHI" src="pytz/zoneinfo/Australia/LHI" />
        <File name="Lindeman" src="pytz/zoneinfo/Australia/Lindeman" />
        <File name="Lord_Howe" src="pytz/zoneinfo/Australia/Lord_Howe" />
        <File name="Melbourne" src="pytz/zoneinfo/Australia/Melbourne" />
        <File name="NSW" src="pytz/zoneinfo/Australia/NSW" />
        <File name="North" src="pytz/zoneinfo/Australia/North" />
        <File name="Perth" src="pytz/zoneinfo/Australia/Perth" />
        <File name="Queensland" src="pytz/zoneinfo/Australia/Queensland" />
        <File name="South" src="pytz/zoneinfo/Australia/South" />
        <File name="Sydney" src="pytz/zoneinfo/Australia/Sydney" />
        <File name="Tasmania" src="pytz/zoneinfo/Australia/Tasmania" />
        <File name="Victoria" src="pytz/zoneinfo/Australia/Victoria" />
        <File name="West" src="pytz/zoneinfo/Australia/West" />
        <File name="Yancowinna" src="pytz/zoneinfo/Australia/Yancowinna" />
        <File name="Acre" src="pytz/zoneinfo/Brazil/Acre" />
        <File name="DeNoronha" src="pytz/zoneinfo/Brazil/DeNoronha" />
        <File name="East" src="pytz/zoneinfo/Brazil/East" />
        <File name="West" src="pytz/zoneinfo/Brazil/West" />
        <File name="CET" src="pytz/zoneinfo/CET" />
        <File name="CST6CDT" src="pytz/zoneinfo/CST6CDT" />
        <File name="Atlantic" src="pytz/zoneinfo/Canada/Atlantic" />
        <File name="Central" src="pytz/zoneinfo/Canada/Central" />
        <File name="East-Saskatchewan" src="pytz/zoneinfo/Canada/East-Saskatchewan" />
        <File name="Eastern" src="pytz/zoneinfo/Canada/Eastern" />
        <File name="Mountain" src="pytz/zoneinfo/Canada/Mountain" />
        <File name="Newfoundland" src="pytz/zoneinfo/Canada/Newfoundland" />
        <File name="Pacific" src="pytz/zoneinfo/Canada/Pacific" />
        <File name="Saskatchewan" src="pytz/zoneinfo/Canada/Saskatchewan" />
        <File name="Yukon" src="pytz/zoneinfo/Canada/Yukon" />
        <File name="Continental" src="pytz/zoneinfo/Chile/Continental" />
        <File name="EasterIsland" src="pytz/zoneinfo/Chile/EasterIsland" />
        <File name="Cuba" src="pytz/zoneinfo/Cuba" />
        <File name="EET" src="pytz/zoneinfo/EET" />
        <File name="EST" src="pytz/zoneinfo/EST" />
        <File name="EST5EDT" src="pytz/zoneinfo/EST5EDT" />
        <File name="Egypt" src="pytz/zoneinfo/Egypt" />
        <File name="Eire" src="pytz/zoneinfo/Eire" />
        <File name="GMT" src="pytz/zoneinfo/Etc/GMT" />
        <File name="GMT+0" src="pytz/zoneinfo/Etc/GMT+0" />
        <File name="GMT+1" src="pytz/zoneinfo/Etc/GMT+1" />
        <File name="GMT+10" src="pytz/zoneinfo/Etc/GMT+10" />
        <File name="GMT+11" src="pytz/zoneinfo/Etc/GMT+11" />
        <File name="GMT+12" src="pytz/zoneinfo/Etc/GMT+12" />
        <File name="GMT+2" src="pytz/zoneinfo/Etc/GMT+2" />
        <File name="GMT+3" src="pytz/zoneinfo/Etc/GMT+3" />
        <File name="GMT+4" src="pytz/zoneinfo/Etc/GMT+4" />
        <File name="GMT+5" src="pytz/zoneinfo/Etc/GMT+5" />
        <File name="GMT+6" src="pytz/zoneinfo/Etc/GMT+6" />
        <File name="GMT+7" src="pytz/zoneinfo/Etc/GMT+7" />
        <File name="GMT+8" src="pytz/zoneinfo/Etc/GMT+8" />
        <File name="GMT+9" src="pytz/zoneinfo/Etc/GMT+9" />
        <File name="GMT-0" src="pytz/zoneinfo/Etc/GMT-0" />
        <File name="GMT-1" src="pytz/zoneinfo/Etc/GMT-1" />
        <File name="GMT-10" src="pytz/zoneinfo/Etc/GMT-10" />
        <File name="GMT-11" src="pytz/zoneinfo/Etc/GMT-11" />
        <File name="GMT-12" src="pytz/zoneinfo/Etc/GMT-12" />
        <File name="GMT-13" src="pytz/zoneinfo/Etc/GMT-13" />
        <File name="GMT-14" src="pytz/zoneinfo/Etc/GMT-14" />
        <File name="GMT-2" src="pytz/zoneinfo/Etc/GMT-2" />
        <File name="GMT-3" src="pytz/zoneinfo/Etc/GMT-3" />
        <File name="GMT-4" src="pytz/zoneinfo/Etc/GMT-4" />
        <File name="GMT-5" src="pytz/zoneinfo/Etc/GMT-5" />
        <File name="GMT-6" src="pytz/zoneinfo/Etc/GMT-6" />
        <File name="GMT-7" src="pytz/zoneinfo/Etc/GMT-7" />
        <File name="GMT-8" src="pytz/zoneinfo/Etc/GMT-8" />
        <File name="GMT-9" src="pytz/zoneinfo/Etc/GMT-9" />
        <File name="GMT0" src="pytz/zoneinfo/Etc/GMT0" />
        <File name="Greenwich" src="pytz/zoneinfo/Etc/Greenwich" />
        <File name="UCT" src="pytz/zoneinfo/Etc/UCT" />
        <File name="UTC" src="pytz/zoneinfo/Etc/UTC" />
        <File name="Universal" src="pytz/zoneinfo/Etc/Universal" />
        <File name="Zulu" src="pytz/zoneinfo/Etc/Zulu" />
        <File name="Amsterdam" src="pytz/zoneinfo/Europe/Amsterdam" />
        <File name="Andorra" src="pytz/zoneinfo/Europe/Andorra" />
        <File name="Astrakhan" src="pytz/zoneinfo/Europe/Astrakhan" />
        <File name="Athens" src="pytz/zoneinfo/Europe/Athens" />
        <File name="Belfast" src="pytz/zoneinfo/Europe/Belfast" />
        <File name="Belgrade" src="pytz/zoneinfo/Europe/Belgrade" />
        <File name="Berlin" src="pytz/zoneinfo/Europe/Berlin" />
        <File name="Bratislava" src="pytz/zoneinfo/Europe/Bratislava" />
        <File name="Brussels" src="pytz/zoneinfo/Europe/Brussels" />
        <File name="Bucharest" src="pytz/zoneinfo/Europe/Bucharest" />
        <File name="Budapest" src="pytz/zoneinfo/Europe/Budapest" />
        <File name="Busingen" src="pytz/zoneinfo/Europe/Busingen" />
        <File name="Chisinau" src="pytz/zoneinfo/Europe/Chisinau" />
        <File name="Copenhagen" src="pytz/zoneinfo/Europe/Copenhagen" />
        <File name="Dublin" src="pytz/zoneinfo/Europe/Dublin" />
        <File name="Gibraltar" src="pytz/zoneinfo/Europe/Gibraltar" />
        <File name="Guernsey" src="pytz/zoneinfo/Europe/Guernsey" />
        <File name="Helsinki" src="pytz/zoneinfo/Europe/Helsinki" />
        <File name="Isle_of_Man" src="pytz/zoneinfo/Europe/Isle_of_Man" />
        <File name="Istanbul" src="pytz/zoneinfo/Europe/Istanbul" />
        <File name="Jersey" src="pytz/zoneinfo/Europe/Jersey" />
        <File name="Kaliningrad" src="pytz/zoneinfo/Europe/Kaliningrad" />
        <File name="Kiev" src="pytz/zoneinfo/Europe/Kiev" />
        <File name="Kirov" src="pytz/zoneinfo/Europe/Kirov" />
        <File name="Lisbon" src="pytz/zoneinfo/Europe/Lisbon" />
        <File name="Ljubljana" src="pytz/zoneinfo/Europe/Ljubljana" />
        <File name="London" src="pytz/zoneinfo/Europe/London" />
        <File name="Luxembourg" src="pytz/zoneinfo/Europe/Luxembourg" />
        <File name="Madrid" src="pytz/zoneinfo/Europe/Madrid" />
        <File name="Malta" src="pytz/zoneinfo/Europe/Malta" />
        <File name="Mariehamn" src="pytz/zoneinfo/Europe/Mariehamn" />
        <File name="Minsk" src="pytz/zoneinfo/Europe/Minsk" />
        <File name="Monaco" src="pytz/zoneinfo/Europe/Monaco" />
        <File name="Moscow" src="pytz/zoneinfo/Europe/Moscow" />
        <File name="Nicosia" src="pytz/zoneinfo/Europe/Nicosia" />
        <File name="Oslo" src="pytz/zoneinfo/Europe/Oslo" />
        <File name="Paris" src="pytz/zoneinfo/Europe/Paris" />
        <File name="Podgorica" src="pytz/zoneinfo/Europe/Podgorica" />
        <File name="Prague" src="pytz/zoneinfo/Europe/Prague" />
        <File name="Riga" src="pytz/zoneinfo/Europe/Riga" />
        <File name="Rome" src="pytz/zoneinfo/Europe/Rome" />
        <File name="Samara" src="pytz/zoneinfo/Europe/Samara" />
        <File name="San_Marino" src="pytz/zoneinfo/Europe/San_Marino" />
        <File name="Sarajevo" src="pytz/zoneinfo/Europe/Sarajevo" />
        <File name="Saratov" src="pytz/zoneinfo/Europe/Saratov" />
        <File name="Simferopol" src="pytz/zoneinfo/Europe/Simferopol" />
        <File name="Skopje" src="pytz/zoneinfo/Europe/Skopje" />
        <File name="Sofia" src="pytz/zoneinfo/Europe/Sofia" />
        <File name="Stockholm" src="pytz/zoneinfo/Europe/Stockholm" />
        <File name="Tallinn" src="pytz/zoneinfo/Europe/Tallinn" />
        <File name="Tirane" src="pytz/zoneinfo/Europe/Tirane" />
        <File name="Tiraspol" src="pytz/zoneinfo/Europe/Tiraspol" />
        <File name="Ulyanovsk" src="pytz/zoneinfo/Europe/Ulyanovsk" />
        <File name="Uzhgorod" src="pytz/zoneinfo/Europe/Uzhgorod" />
        <File name="Vaduz" src="pytz/zoneinfo/Europe/Vaduz" />
        <File name="Vatican" src="pytz/zoneinfo/Europe/Vatican" />
        <File name="Vienna" src="pytz/zoneinfo/Europe/Vienna" />
        <File name="Vilnius" src="pytz/zoneinfo/Europe/Vilnius" />
        <File name="Volgograd" src="pytz/zoneinfo/Europe/Volgograd" />
        <File name="Warsaw" src="pytz/zoneinfo/Europe/Warsaw" />
        <File name="Zagreb" src="pytz/zoneinfo/Europe/Zagreb" />
        <File name="Zaporozhye" src="pytz/zoneinfo/Europe/Zaporozhye" />
        <File name="Zurich" src="pytz/zoneinfo/Europe/Zurich" />
        <File name="Factory" src="pytz/zoneinfo/Factory" />
        <File name="GB" src="pytz/zoneinfo/GB" />
        <File name="GB-Eire" src="pytz/zoneinfo/GB-Eire" />
        <File name="GMT" src="pytz/zoneinfo/GMT" />
        <File name="GMT+0" src="pytz/zoneinfo/GMT+0" />
        <File name="GMT-0" src="pytz/zoneinfo/GMT-0" />
        <File name="GMT0" src="pytz/zoneinfo/GMT0" />
        <File name="Greenwich" src="pytz/zoneinfo/Greenwich" />
        <File name="HST" src="pytz/zoneinfo/HST" />
        <File name="Hongkong" src="pytz/zoneinfo/Hongkong" />
        <File name="Iceland" src="pytz/zoneinfo/Iceland" />
        <File name="Antananarivo" src="pytz/zoneinfo/Indian/Antananarivo" />
        <File name="Chagos" src="pytz/zoneinfo/Indian/Chagos" />
        <File name="Christmas" src="pytz/zoneinfo/Indian/Christmas" />
        <File name="Cocos" src="pytz/zoneinfo/Indian/Cocos" />
        <File name="Comoro" src="pytz/zoneinfo/Indian/Comoro" />
        <File name="Kerguelen" src="pytz/zoneinfo/Indian/Kerguelen" />
        <File name="Mahe" src="pytz/zoneinfo/Indian/Mahe" />
        <File name="Maldives" src="pytz/zoneinfo/Indian/Maldives" />
        <File name="Mauritius" src="pytz/zoneinfo/Indian/Mauritius" />
        <File name="Mayotte" src="pytz/zoneinfo/Indian/Mayotte" />
        <File name="Reunion" src="pytz/zoneinfo/Indian/Reunion" />
        <File name="Iran" src="pytz/zoneinfo/Iran" />
        <File name="Israel" src="pytz/zoneinfo/Israel" />
        <File name="Jamaica" src="pytz/zoneinfo/Jamaica" />
        <File name="Japan" src="pytz/zoneinfo/Japan" />
        <File name="Kwajalein" src="pytz/zoneinfo/Kwajalein" />
        <File name="Libya" src="pytz/zoneinfo/Libya" />
        <File name="MET" src="pytz/zoneinfo/MET" />
        <File name="MST" src="pytz/zoneinfo/MST" />
        <File name="MST7MDT" src="pytz/zoneinfo/MST7MDT" />
        <File name="BajaNorte" src="pytz/zoneinfo/Mexico/BajaNorte" />
        <File name="BajaSur" src="pytz/zoneinfo/Mexico/BajaSur" />
        <File name="General" src="pytz/zoneinfo/Mexico/General" />
        <File name="NZ" src="pytz/zoneinfo/NZ" />
        <File name="NZ-CHAT" src="pytz/zoneinfo/NZ-CHAT" />
        <File name="Navajo" src="pytz/zoneinfo/Navajo" />
        <File name="PRC" src="pytz/zoneinfo/PRC" />
        <File name="PST8PDT" src="pytz/zoneinfo/PST8PDT" />
        <File name="Apia" src="pytz/zoneinfo/Pacific/Apia" />
        <File name="Auckland" src="pytz/zoneinfo/Pacific/Auckland" />
        <File name="Bougainville" src="pytz/zoneinfo/Pacific/Bougainville" />
        <File name="Chatham" src="pytz/zoneinfo/Pacific/Chatham" />
        <File name="Chuuk" src="pytz/zoneinfo/Pacific/Chuuk" />
        <File name="Easter" src="pytz/zoneinfo/Pacific/Easter" />
        <File name="Efate" src="pytz/zoneinfo/Pacific/Efate" />
        <File name="Enderbury" src="pytz/zoneinfo/Pacific/Enderbury" />
        <File name="Fakaofo" src="pytz/zoneinfo/Pacific/Fakaofo" />
        <File name="Fiji" src="pytz/zoneinfo/Pacific/Fiji" />
        <File name="Funafuti" src="pytz/zoneinfo/Pacific/Funafuti" />
        <File name="Galapagos" src="pytz/zoneinfo/Pacific/Galapagos" />
        <File name="Gambier" src="pytz/zoneinfo/Pacific/Gambier" />
        <File name="Guadalcanal" src="pytz/zoneinfo/Pacific/Guadalcanal" />
        <File name="Guam" src="pytz/zoneinfo/Pacific/Guam" />
        <File name="Honolulu" src="pytz/zoneinfo/Pacific/Honolulu" />
        <File name="Johnston" src="pytz/zoneinfo/Pacific/Johnston" />
        <File name="Kiritimati" src="pytz/zoneinfo/Pacific/Kiritimati" />
        <File name="Kosrae" src="pytz/zoneinfo/Pacific/Kosrae" />
        <File name="Kwajalein" src="pytz/zoneinfo/Pacific/Kwajalein" />
        <File name="Majuro" src="pytz/zoneinfo/Pacific/Majuro" />
        <File name="Marquesas" src="pytz/zoneinfo/Pacific/Marquesas" />
        <File name="Midway" src="pytz/zoneinfo/Pacific/Midway" />
        <File name="Nauru" src="pytz/zoneinfo/Pacific/Nauru" />
        <File name="Niue" src="pytz/zoneinfo/Pacific/Niue" />
        <File name="Norfolk" src="pytz/zoneinfo/Pacific/Norfolk" />
        <File name="Noumea" src="pytz/zoneinfo/Pacific/Noumea" />
        <File name="Pago_Pago" src="pytz/zoneinfo/Pacific/Pago_Pago" />
        <File name="Palau" src="pytz/zoneinfo/Pacific/Palau" />
        <File name="Pitcairn" src="pytz/zoneinfo/Pacific/Pitcairn" />
        <File name="Pohnpei" src="pytz/zoneinfo/Pacific/Pohnpei" />
        <File name="Ponape" src="pytz/zoneinfo/Pacific/Ponape" />
        <File name="Port_Moresby" src="pytz/zoneinfo/Pacific/Port_Moresby" />
        <File name="Rarotonga" src="pytz/zoneinfo/Pacific/Rarotonga" />
        <File name="Saipan" src="pytz/zoneinfo/Pacific/Saipan" />
        <File name="Samoa" src="pytz/zoneinfo/Pacific/Samoa" />
        <File name="Tahiti" src="pytz/zoneinfo/Pacific/Tahiti" />
        <File name="Tarawa" src="pytz/zoneinfo/Pacific/Tarawa" />
        <File name="Tongatapu" src="pytz/zoneinfo/Pacific/Tongatapu" />
        <File name="Truk" src="pytz/zoneinfo/Pacific/Truk" />
        <File name="Wake" src="pytz/zoneinfo/Pacific/Wake" />
        <File name="Wallis" src="pytz/zoneinfo/Pacific/Wallis" />
        <File name="Yap" src="pytz/zoneinfo/Pacific/Yap" />
        <File name="Poland" src="pytz/zoneinfo/Poland" />
        <File name="Portugal" src="pytz/zoneinfo/Portugal" />
        <File name="ROC" src="pytz/zoneinfo/ROC" />
        <File name="ROK" src="pytz/zoneinfo/ROK" />
        <File name="Singapore" src="pytz/zoneinfo/Singapore" />
        <File name="Turkey" src="pytz/zoneinfo/Turkey" />
        <File name="UCT" src="pytz/zoneinfo/UCT" />
        <File name="Alaska" src="pytz/zoneinfo/US/Alaska" />
        <File name="Aleutian" src="pytz/zoneinfo/US/Aleutian" />
        <File name="Arizona" src="pytz/zoneinfo/US/Arizona" />
        <File name="Central" src="pytz/zoneinfo/US/Central" />
        <File name="East-Indiana" src="pytz/zoneinfo/US/East-Indiana" />
        <File name="Eastern" src="pytz/zoneinfo/US/Eastern" />
        <File name="Hawaii" src="pytz/zoneinfo/US/Hawaii" />
        <File name="Indiana-Starke" src="pytz/zoneinfo/US/Indiana-Starke" />
        <File name="Michigan" src="pytz/zoneinfo/US/Michigan" />
        <File name="Mountain" src="pytz/zoneinfo/US/Mountain" />
        <File name="Pacific" src="pytz/zoneinfo/US/Pacific" />
        <File name="Pacific-New" src="pytz/zoneinfo/US/Pacific-New" />
        <File name="Samoa" src="pytz/zoneinfo/US/Samoa" />
        <File name="UTC" src="pytz/zoneinfo/UTC" />
        <File name="Universal" src="pytz/zoneinfo/Universal" />
        <File name="W-SU" src="pytz/zoneinfo/W-SU" />
        <File name="WET" src="pytz/zoneinfo/WET" />
        <File name="Zulu" src="pytz/zoneinfo/Zulu" />
        <File name="iso3166" src="pytz/zoneinfo/iso3166.tab" />
        <File name="localtime" src="pytz/zoneinfo/localtime" />
        <File name="posixrules" src="pytz/zoneinfo/posixrules" />
        <File name="zone" src="pytz/zoneinfo/zone.tab" />
        <File name="zone1970" src="pytz/zoneinfo/zone1970.tab" />
        <File name="qmatic" src="qmatic.py" />
        <File name="__init__" src="twilio/__init__.py" />
        <File name="__init__" src="twilio/__init__.pyc" />
        <File name="__init__" src="twilio/base/__init__.py" />
        <File name="__init__" src="twilio/base/__init__.pyc" />
        <File name="deserialize" src="twilio/base/deserialize.py" />
        <File name="deserialize" src="twilio/base/deserialize.pyc" />
        <File name="domain" src="twilio/base/domain.py" />
        <File name="domain" src="twilio/base/domain.pyc" />
        <File name="exceptions" src="twilio/base/exceptions.py" />
        <File name="exceptions" src="twilio/base/exceptions.pyc" />
        <File name="instance_context" src="twilio/base/instance_context.py" />
        <File name="instance_context" src="twilio/base/instance_context.pyc" />
        <File name="instance_resource" src="twilio/base/instance_resource.py" />
        <File name="instance_resource" src="twilio/base/instance_resource.pyc" />
        <File name="list_resource" src="twilio/base/list_resource.py" />
        <File name="list_resource" src="twilio/base/list_resource.pyc" />
        <File name="page" src="twilio/base/page.py" />
        <File name="page" src="twilio/base/page.pyc" />
        <File name="serialize" src="twilio/base/serialize.py" />
        <File name="serialize" src="twilio/base/serialize.pyc" />
        <File name="values" src="twilio/base/values.py" />
        <File name="values" src="twilio/base/values.pyc" />
        <File name="version" src="twilio/base/version.py" />
        <File name="version" src="twilio/base/version.pyc" />
        <File name="compat" src="twilio/compat.py" />
        <File name="cacert" src="twilio/conf/cacert.pem" />
        <File name="__init__" src="twilio/http/__init__.py" />
        <File name="__init__" src="twilio/http/__init__.pyc" />
        <File name="debug" src="twilio/http/debug.py" />
        <File name="http_client" src="twilio/http/http_client.py" />
        <File name="http_client" src="twilio/http/http_client.pyc" />
        <File name="request" src="twilio/http/request.py" />
        <File name="response" src="twilio/http/response.py" />
        <File name="response" src="twilio/http/response.pyc" />
        <File name="validation_client" src="twilio/http/validation_client.py" />
        <File name="__init__" src="twilio/jwt/__init__.py" />
        <File name="__init__" src="twilio/jwt/access_token/__init__.py" />
        <File name="grants" src="twilio/jwt/access_token/grants.py" />
        <File name="__init__" src="twilio/jwt/client/__init__.py" />
        <File name="compat" src="twilio/jwt/compat.py" />
        <File name="__init__" src="twilio/jwt/taskrouter/__init__.py" />
        <File name="capabilities" src="twilio/jwt/taskrouter/capabilities.py" />
        <File name="__init__" src="twilio/jwt/validation/__init__.py" />
        <File name="request_validator" src="twilio/request_validator.py" />
        <File name="__init__" src="twilio/rest/__init__.py" />
        <File name="__init__" src="twilio/rest/__init__.pyc" />
        <File name="__init__" src="twilio/rest/accounts/__init__.py" />
        <File name="__init__" src="twilio/rest/accounts/v1/__init__.py" />
        <File name="__init__" src="twilio/rest/accounts/v1/credential/__init__.py" />
        <File name="public_key" src="twilio/rest/accounts/v1/credential/public_key.py" />
        <File name="__init__" src="twilio/rest/api/__init__.py" />
        <File name="__init__" src="twilio/rest/api/__init__.pyc" />
        <File name="__init__" src="twilio/rest/api/v2010/__init__.py" />
        <File name="__init__" src="twilio/rest/api/v2010/__init__.pyc" />
        <File name="__init__" src="twilio/rest/api/v2010/account/__init__.py" />
        <File name="__init__" src="twilio/rest/api/v2010/account/__init__.pyc" />
        <File name="__init__" src="twilio/rest/api/v2010/account/address/__init__.py" />
        <File name="__init__" src="twilio/rest/api/v2010/account/address/__init__.pyc" />
        <File name="dependent_phone_number" src="twilio/rest/api/v2010/account/address/dependent_phone_number.py" />
        <File name="dependent_phone_number" src="twilio/rest/api/v2010/account/address/dependent_phone_number.pyc" />
        <File name="application" src="twilio/rest/api/v2010/account/application.py" />
        <File name="application" src="twilio/rest/api/v2010/account/application.pyc" />
        <File name="authorized_connect_app" src="twilio/rest/api/v2010/account/authorized_connect_app.py" />
        <File name="authorized_connect_app" src="twilio/rest/api/v2010/account/authorized_connect_app.pyc" />
        <File name="__init__" src="twilio/rest/api/v2010/account/available_phone_number/__init__.py" />
        <File name="__init__" src="twilio/rest/api/v2010/account/available_phone_number/__init__.pyc" />
        <File name="local" src="twilio/rest/api/v2010/account/available_phone_number/local.py" />
        <File name="local" src="twilio/rest/api/v2010/account/available_phone_number/local.pyc" />
        <File name="mobile" src="twilio/rest/api/v2010/account/available_phone_number/mobile.py" />
        <File name="mobile" src="twilio/rest/api/v2010/account/available_phone_number/mobile.pyc" />
        <File name="toll_free" src="twilio/rest/api/v2010/account/available_phone_number/toll_free.py" />
        <File name="toll_free" src="twilio/rest/api/v2010/account/available_phone_number/toll_free.pyc" />
        <File name="__init__" src="twilio/rest/api/v2010/account/call/__init__.py" />
        <File name="__init__" src="twilio/rest/api/v2010/account/call/__init__.pyc" />
        <File name="feedback" src="twilio/rest/api/v2010/account/call/feedback.py" />
        <File name="feedback" src="twilio/rest/api/v2010/account/call/feedback.pyc" />
        <File name="feedback_summary" src="twilio/rest/api/v2010/account/call/feedback_summary.py" />
        <File name="feedback_summary" src="twilio/rest/api/v2010/account/call/feedback_summary.pyc" />
        <File name="notification" src="twilio/rest/api/v2010/account/call/notification.py" />
        <File name="notification" src="twilio/rest/api/v2010/account/call/notification.pyc" />
        <File name="recording" src="twilio/rest/api/v2010/account/call/recording.py" />
        <File name="recording" src="twilio/rest/api/v2010/account/call/recording.pyc" />
        <File name="__init__" src="twilio/rest/api/v2010/account/conference/__init__.py" />
        <File name="__init__" src="twilio/rest/api/v2010/account/conference/__init__.pyc" />
        <File name="participant" src="twilio/rest/api/v2010/account/conference/participant.py" />
        <File name="participant" src="twilio/rest/api/v2010/account/conference/participant.pyc" />
        <File name="connect_app" src="twilio/rest/api/v2010/account/connect_app.py" />
        <File name="connect_app" src="twilio/rest/api/v2010/account/connect_app.pyc" />
        <File name="__init__" src="twilio/rest/api/v2010/account/incoming_phone_number/__init__.py" />
        <File name="__init__" src="twilio/rest/api/v2010/account/incoming_phone_number/__init__.pyc" />
        <File name="local" src="twilio/rest/api/v2010/account/incoming_phone_number/local.py" />
        <File name="local" src="twilio/rest/api/v2010/account/incoming_phone_number/local.pyc" />
        <File name="mobile" src="twilio/rest/api/v2010/account/incoming_phone_number/mobile.py" />
        <File name="mobile" src="twilio/rest/api/v2010/account/incoming_phone_number/mobile.pyc" />
        <File name="toll_free" src="twilio/rest/api/v2010/account/incoming_phone_number/toll_free.py" />
        <File name="toll_free" src="twilio/rest/api/v2010/account/incoming_phone_number/toll_free.pyc" />
        <File name="key" src="twilio/rest/api/v2010/account/key.py" />
        <File name="key" src="twilio/rest/api/v2010/account/key.pyc" />
        <File name="__init__" src="twilio/rest/api/v2010/account/message/__init__.py" />
        <File name="__init__" src="twilio/rest/api/v2010/account/message/__init__.pyc" />
        <File name="feedback" src="twilio/rest/api/v2010/account/message/feedback.py" />
        <File name="feedback" src="twilio/rest/api/v2010/account/message/feedback.pyc" />
        <File name="media" src="twilio/rest/api/v2010/account/message/media.py" />
        <File name="media" src="twilio/rest/api/v2010/account/message/media.pyc" />
        <File name="new_key" src="twilio/rest/api/v2010/account/new_key.py" />
        <File name="new_key" src="twilio/rest/api/v2010/account/new_key.pyc" />
        <File name="new_signing_key" src="twilio/rest/api/v2010/account/new_signing_key.py" />
        <File name="new_signing_key" src="twilio/rest/api/v2010/account/new_signing_key.pyc" />
        <File name="notification" src="twilio/rest/api/v2010/account/notification.py" />
        <File name="notification" src="twilio/rest/api/v2010/account/notification.pyc" />
        <File name="outgoing_caller_id" src="twilio/rest/api/v2010/account/outgoing_caller_id.py" />
        <File name="outgoing_caller_id" src="twilio/rest/api/v2010/account/outgoing_caller_id.pyc" />
        <File name="__init__" src="twilio/rest/api/v2010/account/queue/__init__.py" />
        <File name="__init__" src="twilio/rest/api/v2010/account/queue/__init__.pyc" />
        <File name="member" src="twilio/rest/api/v2010/account/queue/member.py" />
        <File name="member" src="twilio/rest/api/v2010/account/queue/member.pyc" />
        <File name="__init__" src="twilio/rest/api/v2010/account/recording/__init__.py" />
        <File name="__init__" src="twilio/rest/api/v2010/account/recording/__init__.pyc" />
        <File name="__init__" src="twilio/rest/api/v2010/account/recording/add_on_result/__init__.py" />
        <File name="__init__" src="twilio/rest/api/v2010/account/recording/add_on_result/__init__.pyc" />
        <File name="__init__" src="twilio/rest/api/v2010/account/recording/add_on_result/payload/__init__.py" />
        <File name="__init__" src="twilio/rest/api/v2010/account/recording/add_on_result/payload/__init__.pyc" />
        <File name="transcription" src="twilio/rest/api/v2010/account/recording/transcription.py" />
        <File name="transcription" src="twilio/rest/api/v2010/account/recording/transcription.pyc" />
        <File name="short_code" src="twilio/rest/api/v2010/account/short_code.py" />
        <File name="short_code" src="twilio/rest/api/v2010/account/short_code.pyc" />
        <File name="signing_key" src="twilio/rest/api/v2010/account/signing_key.py" />
        <File name="signing_key" src="twilio/rest/api/v2010/account/signing_key.pyc" />
        <File name="__init__" src="twilio/rest/api/v2010/account/sip/__init__.py" />
        <File name="__init__" src="twilio/rest/api/v2010/account/sip/__init__.pyc" />
        <File name="__init__" src="twilio/rest/api/v2010/account/sip/credential_list/__init__.py" />
        <File name="__init__" src="twilio/rest/api/v2010/account/sip/credential_list/__init__.pyc" />
        <File name="credential" src="twilio/rest/api/v2010/account/sip/credential_list/credential.py" />
        <File name="credential" src="twilio/rest/api/v2010/account/sip/credential_list/credential.pyc" />
        <File name="__init__" src="twilio/rest/api/v2010/account/sip/domain/__init__.py" />
        <File name="__init__" src="twilio/rest/api/v2010/account/sip/domain/__init__.pyc" />
        <File name="credential_list_mapping" src="twilio/rest/api/v2010/account/sip/domain/credential_list_mapping.py" />
        <File name="credential_list_mapping" src="twilio/rest/api/v2010/account/sip/domain/credential_list_mapping.pyc" />
        <File name="ip_access_control_list_mapping" src="twilio/rest/api/v2010/account/sip/domain/ip_access_control_list_mapping.py" />
        <File name="ip_access_control_list_mapping" src="twilio/rest/api/v2010/account/sip/domain/ip_access_control_list_mapping.pyc" />
        <File name="__init__" src="twilio/rest/api/v2010/account/sip/ip_access_control_list/__init__.py" />
        <File name="__init__" src="twilio/rest/api/v2010/account/sip/ip_access_control_list/__init__.pyc" />
        <File name="ip_address" src="twilio/rest/api/v2010/account/sip/ip_access_control_list/ip_address.py" />
        <File name="ip_address" src="twilio/rest/api/v2010/account/sip/ip_access_control_list/ip_address.pyc" />
        <File name="token" src="twilio/rest/api/v2010/account/token.py" />
        <File name="token" src="twilio/rest/api/v2010/account/token.pyc" />
        <File name="transcription" src="twilio/rest/api/v2010/account/transcription.py" />
        <File name="transcription" src="twilio/rest/api/v2010/account/transcription.pyc" />
        <File name="__init__" src="twilio/rest/api/v2010/account/usage/__init__.py" />
        <File name="__init__" src="twilio/rest/api/v2010/account/usage/__init__.pyc" />
        <File name="__init__" src="twilio/rest/api/v2010/account/usage/record/__init__.py" />
        <File name="__init__" src="twilio/rest/api/v2010/account/usage/record/__init__.pyc" />
        <File name="all_time" src="twilio/rest/api/v2010/account/usage/record/all_time.py" />
        <File name="all_time" src="twilio/rest/api/v2010/account/usage/record/all_time.pyc" />
        <File name="daily" src="twilio/rest/api/v2010/account/usage/record/daily.py" />
        <File name="daily" src="twilio/rest/api/v2010/account/usage/record/daily.pyc" />
        <File name="last_month" src="twilio/rest/api/v2010/account/usage/record/last_month.py" />
        <File name="last_month" src="twilio/rest/api/v2010/account/usage/record/last_month.pyc" />
        <File name="monthly" src="twilio/rest/api/v2010/account/usage/record/monthly.py" />
        <File name="monthly" src="twilio/rest/api/v2010/account/usage/record/monthly.pyc" />
        <File name="this_month" src="twilio/rest/api/v2010/account/usage/record/this_month.py" />
        <File name="this_month" src="twilio/rest/api/v2010/account/usage/record/this_month.pyc" />
        <File name="today" src="twilio/rest/api/v2010/account/usage/record/today.py" />
        <File name="today" src="twilio/rest/api/v2010/account/usage/record/today.pyc" />
        <File name="yearly" src="twilio/rest/api/v2010/account/usage/record/yearly.py" />
        <File name="yearly" src="twilio/rest/api/v2010/account/usage/record/yearly.pyc" />
        <File name="yesterday" src="twilio/rest/api/v2010/account/usage/record/yesterday.py" />
        <File name="yesterday" src="twilio/rest/api/v2010/account/usage/record/yesterday.pyc" />
        <File name="trigger" src="twilio/rest/api/v2010/account/usage/trigger.py" />
        <File name="trigger" src="twilio/rest/api/v2010/account/usage/trigger.pyc" />
        <File name="validation_request" src="twilio/rest/api/v2010/account/validation_request.py" />
        <File name="validation_request" src="twilio/rest/api/v2010/account/validation_request.pyc" />
        <File name="__init__" src="twilio/rest/chat/__init__.py" />
        <File name="__init__" src="twilio/rest/chat/v1/__init__.py" />
        <File name="credential" src="twilio/rest/chat/v1/credential.py" />
        <File name="__init__" src="twilio/rest/chat/v1/service/__init__.py" />
        <File name="__init__" src="twilio/rest/chat/v1/service/channel/__init__.py" />
        <File name="invite" src="twilio/rest/chat/v1/service/channel/invite.py" />
        <File name="member" src="twilio/rest/chat/v1/service/channel/member.py" />
        <File name="message" src="twilio/rest/chat/v1/service/channel/message.py" />
        <File name="role" src="twilio/rest/chat/v1/service/role.py" />
        <File name="__init__" src="twilio/rest/chat/v1/service/user/__init__.py" />
        <File name="user_channel" src="twilio/rest/chat/v1/service/user/user_channel.py" />
        <File name="__init__" src="twilio/rest/chat/v2/__init__.py" />
        <File name="credential" src="twilio/rest/chat/v2/credential.py" />
        <File name="__init__" src="twilio/rest/chat/v2/service/__init__.py" />
        <File name="__init__" src="twilio/rest/chat/v2/service/channel/__init__.py" />
        <File name="invite" src="twilio/rest/chat/v2/service/channel/invite.py" />
        <File name="member" src="twilio/rest/chat/v2/service/channel/member.py" />
        <File name="message" src="twilio/rest/chat/v2/service/channel/message.py" />
        <File name="role" src="twilio/rest/chat/v2/service/role.py" />
        <File name="__init__" src="twilio/rest/chat/v2/service/user/__init__.py" />
        <File name="user_channel" src="twilio/rest/chat/v2/service/user/user_channel.py" />
        <File name="__init__" src="twilio/rest/ip_messaging/__init__.py" />
        <File name="__init__" src="twilio/rest/ip_messaging/v1/__init__.py" />
        <File name="credential" src="twilio/rest/ip_messaging/v1/credential.py" />
        <File name="__init__" src="twilio/rest/ip_messaging/v1/service/__init__.py" />
        <File name="__init__" src="twilio/rest/ip_messaging/v1/service/channel/__init__.py" />
        <File name="invite" src="twilio/rest/ip_messaging/v1/service/channel/invite.py" />
        <File name="member" src="twilio/rest/ip_messaging/v1/service/channel/member.py" />
        <File name="message" src="twilio/rest/ip_messaging/v1/service/channel/message.py" />
        <File name="role" src="twilio/rest/ip_messaging/v1/service/role.py" />
        <File name="__init__" src="twilio/rest/ip_messaging/v1/service/user/__init__.py" />
        <File name="user_channel" src="twilio/rest/ip_messaging/v1/service/user/user_channel.py" />
        <File name="__init__" src="twilio/rest/ip_messaging/v2/__init__.py" />
        <File name="credential" src="twilio/rest/ip_messaging/v2/credential.py" />
        <File name="__init__" src="twilio/rest/ip_messaging/v2/service/__init__.py" />
        <File name="__init__" src="twilio/rest/ip_messaging/v2/service/channel/__init__.py" />
        <File name="invite" src="twilio/rest/ip_messaging/v2/service/channel/invite.py" />
        <File name="member" src="twilio/rest/ip_messaging/v2/service/channel/member.py" />
        <File name="message" src="twilio/rest/ip_messaging/v2/service/channel/message.py" />
        <File name="role" src="twilio/rest/ip_messaging/v2/service/role.py" />
        <File name="__init__" src="twilio/rest/ip_messaging/v2/service/user/__init__.py" />
        <File name="user_channel" src="twilio/rest/ip_messaging/v2/service/user/user_channel.py" />
        <File name="__init__" src="twilio/rest/lookups/__init__.py" />
        <File name="__init__" src="twilio/rest/lookups/v1/__init__.py" />
        <File name="phone_number" src="twilio/rest/lookups/v1/phone_number.py" />
        <File name="__init__" src="twilio/rest/monitor/__init__.py" />
        <File name="__init__" src="twilio/rest/monitor/v1/__init__.py" />
        <File name="alert" src="twilio/rest/monitor/v1/alert.py" />
        <File name="event" src="twilio/rest/monitor/v1/event.py" />
        <File name="__init__" src="twilio/rest/pricing/__init__.py" />
        <File name="__init__" src="twilio/rest/pricing/v1/__init__.py" />
        <File name="__init__" src="twilio/rest/pricing/v1/messaging/__init__.py" />
        <File name="country" src="twilio/rest/pricing/v1/messaging/country.py" />
        <File name="__init__" src="twilio/rest/pricing/v1/phone_number/__init__.py" />
        <File name="country" src="twilio/rest/pricing/v1/phone_number/country.py" />
        <File name="__init__" src="twilio/rest/pricing/v1/voice/__init__.py" />
        <File name="country" src="twilio/rest/pricing/v1/voice/country.py" />
        <File name="number" src="twilio/rest/pricing/v1/voice/number.py" />
        <File name="__init__" src="twilio/rest/taskrouter/__init__.py" />
        <File name="__init__" src="twilio/rest/taskrouter/v1/__init__.py" />
        <File name="__init__" src="twilio/rest/taskrouter/v1/workspace/__init__.py" />
        <File name="activity" src="twilio/rest/taskrouter/v1/workspace/activity.py" />
        <File name="event" src="twilio/rest/taskrouter/v1/workspace/event.py" />
        <File name="__init__" src="twilio/rest/taskrouter/v1/workspace/task/__init__.py" />
        <File name="reservation" src="twilio/rest/taskrouter/v1/workspace/task/reservation.py" />
        <File name="task_channel" src="twilio/rest/taskrouter/v1/workspace/task_channel.py" />
        <File name="__init__" src="twilio/rest/taskrouter/v1/workspace/task_queue/__init__.py" />
        <File name="task_queue_statistics" src="twilio/rest/taskrouter/v1/workspace/task_queue/task_queue_statistics.py" />
        <File name="task_queues_statistics" src="twilio/rest/taskrouter/v1/workspace/task_queue/task_queues_statistics.py" />
        <File name="__init__" src="twilio/rest/taskrouter/v1/workspace/worker/__init__.py" />
        <File name="reservation" src="twilio/rest/taskrouter/v1/workspace/worker/reservation.py" />
        <File name="worker_channel" src="twilio/rest/taskrouter/v1/workspace/worker/worker_channel.py" />
        <File name="worker_statistics" src="twilio/rest/taskrouter/v1/workspace/worker/worker_statistics.py" />
        <File name="workers_statistics" src="twilio/rest/taskrouter/v1/workspace/worker/workers_statistics.py" />
        <File name="__init__" src="twilio/rest/taskrouter/v1/workspace/workflow/__init__.py" />
        <File name="workflow_statistics" src="twilio/rest/taskrouter/v1/workspace/workflow/workflow_statistics.py" />
        <File name="workspace_statistics" src="twilio/rest/taskrouter/v1/workspace/workspace_statistics.py" />
        <File name="__init__" src="twilio/rest/trunking/__init__.py" />
        <File name="__init__" src="twilio/rest/trunking/v1/__init__.py" />
        <File name="__init__" src="twilio/rest/trunking/v1/trunk/__init__.py" />
        <File name="credential_list" src="twilio/rest/trunking/v1/trunk/credential_list.py" />
        <File name="ip_access_control_list" src="twilio/rest/trunking/v1/trunk/ip_access_control_list.py" />
        <File name="origination_url" src="twilio/rest/trunking/v1/trunk/origination_url.py" />
        <File name="phone_number" src="twilio/rest/trunking/v1/trunk/phone_number.py" />
        <File name="__init__" src="twilio/twiml/__init__.py" />
        <File name="messaging_response" src="twilio/twiml/messaging_response.py" />
        <File name="voice_response" src="twilio/twiml/voice_response.py" />
        <File name="switch" src="html/default/switch.jpg" />
        <File name="main" src="html/css/main.css" />
        <File name="bg" src="html/img/bg.png" />
        <File name="bgNoLogo" src="html/img/bgNoLogo.png" />
        <File name="buttonsBg" src="html/img/buttonsBg.png" />
        <File name="leftArrow" src="html/img/leftArrow.png" />
        <File name="loading" src="html/img/loading.gif" />
        <File name="rightArrow" src="html/img/rightArrow.png" />
    </Resources>
    <Topics>
        <Topic name="qmatic_enu" src="qmatic/qmatic_enu.top" topicName="qmatic" language="en_US" />
    </Topics>
    <IgnoredPaths />
    <Translations auto-fill="en_US">
        <Translation name="translation_en_US" src="translations/translation_en_US.ts" language="en_US" />
    </Translations>
</Package>
